name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: infra/Dockerfile
        push: false
        load: true
        tags: hello:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run tests in Docker
      run: |
        docker run --rm hello:latest npm test -- --watchAll=false

    - name: Run lint in Docker
      run: |
        docker run --rm hello:latest npm run lint

    - name: Build app in Docker
      run: |
        docker run --rm -v $(pwd)/build:/app/build hello:latest npm run build